version: 2
jobs:
  test_php:
    working_directory: /srv
    docker:
      - image: lastcallmedia/php:7.0-dev
    steps:
      - checkout
      - restore_cache:
          key: composer-v2-{{ checksum "composer.json" }}
      - run: composer install
      - save_cache:
          key: composer-v2-{{ checksum "composer.json" }}
          paths: [vendor]
      - run: |
          COMMIT_RANGE=`echo $CIRCLE_COMPARE_URL | cut -d/ -f7`
          IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")); unset IFS
          vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}"
      - run: vendor/bin/phpunit

  test_ui:
    working_directory: /srv
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          key: package-v2-{{ checksum "ui/package.json" }}
      - run: cd ui && npm install
      - save_cache:
          key: package-v2-{{ checksum "ui/package.json" }}
          paths: [ui/node_modules]
      - run: cd ui && npm run test


  deploy_split:
    working_directory: /srv
    docker:
      - image: jderusse/gitsplit
    steps:
      - checkout
      - run: gitsplit

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test_php
      - test_ui
      - deploy_split:
          requires: [test_php]