version: 2
jobs:
  build:
    working_directory: ~/mannequin
    docker:
      - image: lastcallmedia/php:7.0-dev
    steps:
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "composer.json" }}
      - run: composer install
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths: [vendor]

      - restore_cache:
          key: package-v1-{{ checksum "ui/package.json" }}
      - run: cd ui && npm install
      - save_cache:
          key: package-v1-{{ checksum "ui/package.json" }}
          paths: [ui/node_modules]

      - run: vendor/bin/phpunit
      - run: cd ui && npm run test
